# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: $(Build.BuildId)
  imageName: democontainer_poc

stages:
  - stage: Build
    displayName: 'Build and push the Docker image'
    jobs:
      - job: BuildAndPush
        displayName: 'Build and push the jobs'

        steps:

          - task: Docker@2
            displayName: 'Login the container registry'
            inputs:
             command: 'login'
             containerRegistry: 'nitish-test-acr-spo'

          - task: Docker@2
            displayName: 'Build the Docker image'
            inputs:
              repository: '$(imageName)'
              command: 'build'
              Dockerfile: '$(Build.sourcesDirectory)/Dockerfile'
              tags: |
                $(tag)
                latest
          
          - task: Docker@2
            displayName: 'Push the Docker image'
            inputs:
              containerRegistry: 'nitish-test-acr-spo'
              repository: '$(imageName)'
              command: 'push'
              tags: |
                $(tag)
                latest